services:

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    restart: on-failure
    env_file:
      - .env
    secrets: #delete unused
      - DB_ADMIN_PASSWORD
      - DB_PASSWORD
      - DB_ROOT_PASSWORD
      - WP_ADMIN_PASSWORD
      - WP_PASSWORD
    networks:
      - inception
    healthcheck:
      test: ["CMD", "test", "-f", "/.done"]
      interval: 1s
      timeout: 1s
      retries: 1000
      start_period: 1s
    volumes:
      - /home/ahekinci/data/mariadb:/var/lib/mysql

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    restart: on-failure
    depends_on:
      mariadb:
        condition: service_healthy
    env_file:
      - .env
    secrets: # delete unused 
      - DB_ADMIN_PASSWORD
      - DB_PASSWORD
      - DB_ROOT_PASSWORD
      - WP_ADMIN_PASSWORD
      - WP_PASSWORD
    networks:
      - inception
    volumes:
      - /home/ahekinci/data/wordpress:/var/www/html/wordpress
  
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    restart: on-failure
    depends_on:
      - wordpress
    env_file:
      - .env
    secrets: #delete
      - DB_ADMIN_PASSWORD
      - DB_PASSWORD
      - DB_ROOT_PASSWORD
      - WP_ADMIN_PASSWORD
      - WP_PASSWORD
    networks:
      - inception

networks:
  inception:

secrets:
  DB_ADMIN_PASSWORD:
    file: ../secrets/db_admin_password.txt
  DB_PASSWORD:
    file: ../secrets/db_password.txt
  DB_ROOT_PASSWORD:
    file: ../secrets/db_root_password.txt
  WP_ADMIN_PASSWORD:
    file: ../secrets/wp_admin_password.txt
  WP_PASSWORD:
    file: ../secrets/wp_password.txt